<?php
/**
 * ErrorCode
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Speech Services API v3.1
 *
 * Speech Services API v3.1.
 *
 * OpenAPI spec version: v3.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.29
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;
use \Swagger\Client\ObjectSerializer;

/**
 * ErrorCode Class Doc Comment
 *
 * @category Class
 * @description High level error codes.
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ErrorCode
{
    /**
     * Possible values of this enum
     */
    const INVALID_REQUEST = 'InvalidRequest';
    const INVALID_ARGUMENT = 'InvalidArgument';
    const INTERNAL_SERVER_ERROR = 'InternalServerError';
    const SERVICE_UNAVAILABLE = 'ServiceUnavailable';
    const NOT_FOUND = 'NotFound';
    const PIPELINE_ERROR = 'PipelineError';
    const CONFLICT = 'Conflict';
    const INTERNAL_COMMUNICATION_FAILED = 'InternalCommunicationFailed';
    const FORBIDDEN = 'Forbidden';
    const NOT_ALLOWED = 'NotAllowed';
    const UNAUTHORIZED = 'Unauthorized';
    const UNSUPPORTED_MEDIA_TYPE = 'UnsupportedMediaType';
    const TOO_MANY_REQUESTS = 'TooManyRequests';
    const UNPROCESSABLE_ENTITY = 'UnprocessableEntity';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::INVALID_REQUEST,
            self::INVALID_ARGUMENT,
            self::INTERNAL_SERVER_ERROR,
            self::SERVICE_UNAVAILABLE,
            self::NOT_FOUND,
            self::PIPELINE_ERROR,
            self::CONFLICT,
            self::INTERNAL_COMMUNICATION_FAILED,
            self::FORBIDDEN,
            self::NOT_ALLOWED,
            self::UNAUTHORIZED,
            self::UNSUPPORTED_MEDIA_TYPE,
            self::TOO_MANY_REQUESTS,
            self::UNPROCESSABLE_ENTITY,
        ];
    }
}


