<?php
/**
 * ProjectProperties
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Speech Services API v3.1
 *
 * Speech Services API v3.1.
 *
 * OpenAPI spec version: v3.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.29
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * ProjectProperties Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ProjectProperties implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'ProjectProperties';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'dataset_count' => 'int',
        'evaluation_count' => 'int',
        'model_count' => 'int',
        'transcription_count' => 'int',
        'endpoint_count' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'dataset_count' => 'int32',
        'evaluation_count' => 'int32',
        'model_count' => 'int32',
        'transcription_count' => 'int32',
        'endpoint_count' => 'int32'
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'dataset_count' => 'datasetCount',
        'evaluation_count' => 'evaluationCount',
        'model_count' => 'modelCount',
        'transcription_count' => 'transcriptionCount',
        'endpoint_count' => 'endpointCount'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'dataset_count' => 'setDatasetCount',
        'evaluation_count' => 'setEvaluationCount',
        'model_count' => 'setModelCount',
        'transcription_count' => 'setTranscriptionCount',
        'endpoint_count' => 'setEndpointCount'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'dataset_count' => 'getDatasetCount',
        'evaluation_count' => 'getEvaluationCount',
        'model_count' => 'getModelCount',
        'transcription_count' => 'getTranscriptionCount',
        'endpoint_count' => 'getEndpointCount'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['dataset_count'] = isset($data['dataset_count']) ? $data['dataset_count'] : null;
        $this->container['evaluation_count'] = isset($data['evaluation_count']) ? $data['evaluation_count'] : null;
        $this->container['model_count'] = isset($data['model_count']) ? $data['model_count'] : null;
        $this->container['transcription_count'] = isset($data['transcription_count']) ? $data['transcription_count'] : null;
        $this->container['endpoint_count'] = isset($data['endpoint_count']) ? $data['endpoint_count'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets dataset_count
     *
     * @return int
     */
    public function getDatasetCount()
    {
        return $this->container['dataset_count'];
    }

    /**
     * Sets dataset_count
     *
     * @param int $dataset_count The number of datasets associated to this project.
     *
     * @return $this
     */
    public function setDatasetCount($dataset_count)
    {
        $this->container['dataset_count'] = $dataset_count;

        return $this;
    }

    /**
     * Gets evaluation_count
     *
     * @return int
     */
    public function getEvaluationCount()
    {
        return $this->container['evaluation_count'];
    }

    /**
     * Sets evaluation_count
     *
     * @param int $evaluation_count The number of evaluations associated to this project.
     *
     * @return $this
     */
    public function setEvaluationCount($evaluation_count)
    {
        $this->container['evaluation_count'] = $evaluation_count;

        return $this;
    }

    /**
     * Gets model_count
     *
     * @return int
     */
    public function getModelCount()
    {
        return $this->container['model_count'];
    }

    /**
     * Sets model_count
     *
     * @param int $model_count The number of models associated to this project.
     *
     * @return $this
     */
    public function setModelCount($model_count)
    {
        $this->container['model_count'] = $model_count;

        return $this;
    }

    /**
     * Gets transcription_count
     *
     * @return int
     */
    public function getTranscriptionCount()
    {
        return $this->container['transcription_count'];
    }

    /**
     * Sets transcription_count
     *
     * @param int $transcription_count The number of transcriptions associated to this project.
     *
     * @return $this
     */
    public function setTranscriptionCount($transcription_count)
    {
        $this->container['transcription_count'] = $transcription_count;

        return $this;
    }

    /**
     * Gets endpoint_count
     *
     * @return int
     */
    public function getEndpointCount()
    {
        return $this->container['endpoint_count'];
    }

    /**
     * Sets endpoint_count
     *
     * @param int $endpoint_count The number of endpoints associated to this project.
     *
     * @return $this
     */
    public function setEndpointCount($endpoint_count)
    {
        $this->container['endpoint_count'] = $endpoint_count;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


