<?php
/**
 * PunctuationMode
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Speech Services API v3.1
 *
 * Speech Services API v3.1.
 *
 * OpenAPI spec version: v3.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.29
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;
use \Swagger\Client\ObjectSerializer;

/**
 * PunctuationMode Class Doc Comment
 *
 * @category Class
 * @description The mode used for punctuation.
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PunctuationMode
{
    /**
     * Possible values of this enum
     */
    const NONE = 'None';
    const DICTATED = 'Dictated';
    const AUTOMATIC = 'Automatic';
    const DICTATED_AND_AUTOMATIC = 'DictatedAndAutomatic';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::NONE,
            self::DICTATED,
            self::AUTOMATIC,
            self::DICTATED_AND_AUTOMATIC,
        ];
    }
}


