<?php
/**
 * EndpointLinksTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Speech Services API v3.1
 *
 * Speech Services API v3.1.
 *
 * OpenAPI spec version: v3.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.29
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * EndpointLinksTest Class Doc Comment
 *
 * @category    Class
 * @description EndpointLinks
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class EndpointLinksTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "EndpointLinks"
     */
    public function testEndpointLinks()
    {
    }

    /**
     * Test attribute "rest_interactive"
     */
    public function testPropertyRestInteractive()
    {
    }

    /**
     * Test attribute "rest_conversation"
     */
    public function testPropertyRestConversation()
    {
    }

    /**
     * Test attribute "rest_dictation"
     */
    public function testPropertyRestDictation()
    {
    }

    /**
     * Test attribute "web_socket_interactive"
     */
    public function testPropertyWebSocketInteractive()
    {
    }

    /**
     * Test attribute "web_socket_conversation"
     */
    public function testPropertyWebSocketConversation()
    {
    }

    /**
     * Test attribute "web_socket_dictation"
     */
    public function testPropertyWebSocketDictation()
    {
    }

    /**
     * Test attribute "logs"
     */
    public function testPropertyLogs()
    {
    }
}
