<?php
/**
 * EvaluationPropertiesTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Speech Services API v3.1
 *
 * Speech Services API v3.1.
 *
 * OpenAPI spec version: v3.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.29
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * EvaluationPropertiesTest Class Doc Comment
 *
 * @category    Class
 * @description EvaluationProperties
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class EvaluationPropertiesTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "EvaluationProperties"
     */
    public function testEvaluationProperties()
    {
    }

    /**
     * Test attribute "word_error_rate2"
     */
    public function testPropertyWordErrorRate2()
    {
    }

    /**
     * Test attribute "word_error_rate1"
     */
    public function testPropertyWordErrorRate1()
    {
    }

    /**
     * Test attribute "sentence_error_rate2"
     */
    public function testPropertySentenceErrorRate2()
    {
    }

    /**
     * Test attribute "sentence_count2"
     */
    public function testPropertySentenceCount2()
    {
    }

    /**
     * Test attribute "word_count2"
     */
    public function testPropertyWordCount2()
    {
    }

    /**
     * Test attribute "correct_word_count2"
     */
    public function testPropertyCorrectWordCount2()
    {
    }

    /**
     * Test attribute "word_substitution_count2"
     */
    public function testPropertyWordSubstitutionCount2()
    {
    }

    /**
     * Test attribute "word_deletion_count2"
     */
    public function testPropertyWordDeletionCount2()
    {
    }

    /**
     * Test attribute "word_insertion_count2"
     */
    public function testPropertyWordInsertionCount2()
    {
    }

    /**
     * Test attribute "sentence_error_rate1"
     */
    public function testPropertySentenceErrorRate1()
    {
    }

    /**
     * Test attribute "sentence_count1"
     */
    public function testPropertySentenceCount1()
    {
    }

    /**
     * Test attribute "word_count1"
     */
    public function testPropertyWordCount1()
    {
    }

    /**
     * Test attribute "correct_word_count1"
     */
    public function testPropertyCorrectWordCount1()
    {
    }

    /**
     * Test attribute "word_substitution_count1"
     */
    public function testPropertyWordSubstitutionCount1()
    {
    }

    /**
     * Test attribute "word_deletion_count1"
     */
    public function testPropertyWordDeletionCount1()
    {
    }

    /**
     * Test attribute "word_insertion_count1"
     */
    public function testPropertyWordInsertionCount1()
    {
    }

    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {
    }

    /**
     * Test attribute "error"
     */
    public function testPropertyError()
    {
    }
}
