<?php
/**
 * ProjectPropertiesTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Speech Services API v3.1
 *
 * Speech Services API v3.1.
 *
 * OpenAPI spec version: v3.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.29
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ProjectPropertiesTest Class Doc Comment
 *
 * @category    Class
 * @description ProjectProperties
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ProjectPropertiesTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ProjectProperties"
     */
    public function testProjectProperties()
    {
    }

    /**
     * Test attribute "dataset_count"
     */
    public function testPropertyDatasetCount()
    {
    }

    /**
     * Test attribute "evaluation_count"
     */
    public function testPropertyEvaluationCount()
    {
    }

    /**
     * Test attribute "model_count"
     */
    public function testPropertyModelCount()
    {
    }

    /**
     * Test attribute "transcription_count"
     */
    public function testPropertyTranscriptionCount()
    {
    }

    /**
     * Test attribute "endpoint_count"
     */
    public function testPropertyEndpointCount()
    {
    }
}
