<?php
/**
 * TranscriptionPropertiesTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Speech Services API v3.1
 *
 * Speech Services API v3.1.
 *
 * OpenAPI spec version: v3.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.29
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * TranscriptionPropertiesTest Class Doc Comment
 *
 * @category    Class
 * @description TranscriptionProperties
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TranscriptionPropertiesTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "TranscriptionProperties"
     */
    public function testTranscriptionProperties()
    {
    }

    /**
     * Test attribute "diarization_enabled"
     */
    public function testPropertyDiarizationEnabled()
    {
    }

    /**
     * Test attribute "word_level_timestamps_enabled"
     */
    public function testPropertyWordLevelTimestampsEnabled()
    {
    }

    /**
     * Test attribute "display_form_word_level_timestamps_enabled"
     */
    public function testPropertyDisplayFormWordLevelTimestampsEnabled()
    {
    }

    /**
     * Test attribute "duration"
     */
    public function testPropertyDuration()
    {
    }

    /**
     * Test attribute "channels"
     */
    public function testPropertyChannels()
    {
    }

    /**
     * Test attribute "destination_container_url"
     */
    public function testPropertyDestinationContainerUrl()
    {
    }

    /**
     * Test attribute "punctuation_mode"
     */
    public function testPropertyPunctuationMode()
    {
    }

    /**
     * Test attribute "profanity_filter_mode"
     */
    public function testPropertyProfanityFilterMode()
    {
    }

    /**
     * Test attribute "time_to_live"
     */
    public function testPropertyTimeToLive()
    {
    }

    /**
     * Test attribute "diarization"
     */
    public function testPropertyDiarization()
    {
    }

    /**
     * Test attribute "language_identification"
     */
    public function testPropertyLanguageIdentification()
    {
    }

    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {
    }

    /**
     * Test attribute "error"
     */
    public function testPropertyError()
    {
    }
}
