<?php
/**
 * CustomSpeechModelEvaluationsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Speech Services API v3.1
 *
 * Speech Services API v3.1.
 *
 * OpenAPI spec version: v3.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.29
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * CustomSpeechModelEvaluationsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CustomSpeechModelEvaluationsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for evaluationsCreate
     *
     * Creates a new evaluation..
     *
     */
    public function testEvaluationsCreate()
    {
    }

    /**
     * Test case for evaluationsDelete
     *
     * Deletes the evaluation identified by the given ID..
     *
     */
    public function testEvaluationsDelete()
    {
    }

    /**
     * Test case for evaluationsGet
     *
     * Gets the evaluation identified by the given ID..
     *
     */
    public function testEvaluationsGet()
    {
    }

    /**
     * Test case for evaluationsGetFile
     *
     * Gets one specific file (identified with fileId) from an evaluation (identified with id)..
     *
     */
    public function testEvaluationsGetFile()
    {
    }

    /**
     * Test case for evaluationsList
     *
     * Gets the list of evaluations for the authenticated subscription..
     *
     */
    public function testEvaluationsList()
    {
    }

    /**
     * Test case for evaluationsListFiles
     *
     * Gets the files of the evaluation identified by the given ID..
     *
     */
    public function testEvaluationsListFiles()
    {
    }

    /**
     * Test case for evaluationsListSupportedLocales
     *
     * Gets a list of supported locales for evaluations..
     *
     */
    public function testEvaluationsListSupportedLocales()
    {
    }

    /**
     * Test case for evaluationsUpdate
     *
     * Updates the mutable details of the evaluation identified by its id..
     *
     */
    public function testEvaluationsUpdate()
    {
    }
}
