<?php
/**
 * CustomSpeechProjectsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Speech Services API v3.1
 *
 * Speech Services API v3.1.
 *
 * OpenAPI spec version: v3.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.29
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * CustomSpeechProjectsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CustomSpeechProjectsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for projectsCreate
     *
     * Creates a new project..
     *
     */
    public function testProjectsCreate()
    {
    }

    /**
     * Test case for projectsDelete
     *
     * Deletes the project identified by the given ID..
     *
     */
    public function testProjectsDelete()
    {
    }

    /**
     * Test case for projectsGet
     *
     * Gets the project identified by the given ID..
     *
     */
    public function testProjectsGet()
    {
    }

    /**
     * Test case for projectsList
     *
     * Gets the list of projects for the authenticated subscription..
     *
     */
    public function testProjectsList()
    {
    }

    /**
     * Test case for projectsListDatasets
     *
     * Gets the list of datasets for specified project..
     *
     */
    public function testProjectsListDatasets()
    {
    }

    /**
     * Test case for projectsListEndpoints
     *
     * Gets the list of endpoints for specified project..
     *
     */
    public function testProjectsListEndpoints()
    {
    }

    /**
     * Test case for projectsListEvaluations
     *
     * Gets the list of evaluations for specified project..
     *
     */
    public function testProjectsListEvaluations()
    {
    }

    /**
     * Test case for projectsListModels
     *
     * Gets the list of models for specified project..
     *
     */
    public function testProjectsListModels()
    {
    }

    /**
     * Test case for projectsListSupportedLocales
     *
     * Gets the list of supported locales..
     *
     */
    public function testProjectsListSupportedLocales()
    {
    }

    /**
     * Test case for projectsListTranscriptions
     *
     * Gets the list of transcriptions for specified project..
     *
     */
    public function testProjectsListTranscriptions()
    {
    }

    /**
     * Test case for projectsUpdate
     *
     * Updates the project identified by the given ID..
     *
     */
    public function testProjectsUpdate()
    {
    }
}
