<?php
/**
 * CustomSpeechWebHooksApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Speech Services API v3.1
 *
 * Speech Services API v3.1.
 *
 * OpenAPI spec version: v3.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.29
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * CustomSpeechWebHooksApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CustomSpeechWebHooksApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for webHooksCreate
     *
     * Creates a new web hook..
     *
     */
    public function testWebHooksCreate()
    {
    }

    /**
     * Test case for webHooksDelete
     *
     * Deletes the web hook identified by the given ID..
     *
     */
    public function testWebHooksDelete()
    {
    }

    /**
     * Test case for webHooksGet
     *
     * Gets the web hook identified by the given ID..
     *
     */
    public function testWebHooksGet()
    {
    }

    /**
     * Test case for webHooksList
     *
     * Gets the list of web hooks for the authenticated subscription..
     *
     */
    public function testWebHooksList()
    {
    }

    /**
     * Test case for webHooksPing
     *
     * Sends a ping event to the registered URL..
     *
     */
    public function testWebHooksPing()
    {
    }

    /**
     * Test case for webHooksTest
     *
     * Sends a request for each registered event type to the registered URL..
     *
     */
    public function testWebHooksTest()
    {
    }

    /**
     * Test case for webHooksUpdate
     *
     * Updates the web hook identified by the given ID..
     *
     */
    public function testWebHooksUpdate()
    {
    }
}
