<?php
/**
 * CustomSpeechEndpointsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Speech Services API v3.1
 *
 * Speech Services API v3.1.
 *
 * OpenAPI spec version: v3.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.29
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * CustomSpeechEndpointsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CustomSpeechEndpointsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for endpointsCreate
     *
     * Creates a new endpoint..
     *
     */
    public function testEndpointsCreate()
    {
    }

    /**
     * Test case for endpointsDelete
     *
     * Deletes the endpoint identified by the given ID..
     *
     */
    public function testEndpointsDelete()
    {
    }

    /**
     * Test case for endpointsDeleteBaseModelLog
     *
     * Deletes one audio or transcription log that have been stored when using the default base model of a given language..
     *
     */
    public function testEndpointsDeleteBaseModelLog()
    {
    }

    /**
     * Test case for endpointsDeleteBaseModelLogs
     *
     * Deletes the specified audio and transcription logs that have been stored when using the default base model of a given language. It deletes all logs before (and including) a specific day..
     *
     */
    public function testEndpointsDeleteBaseModelLogs()
    {
    }

    /**
     * Test case for endpointsDeleteLog
     *
     * Deletes one audio or transcription log that have been stored for a given endpoint..
     *
     */
    public function testEndpointsDeleteLog()
    {
    }

    /**
     * Test case for endpointsDeleteLogs
     *
     * Deletes the specified audio and transcription logs that have been stored for a given endpoint. It deletes all logs before (and including) a specific day..
     *
     */
    public function testEndpointsDeleteLogs()
    {
    }

    /**
     * Test case for endpointsGet
     *
     * Gets the endpoint identified by the given ID..
     *
     */
    public function testEndpointsGet()
    {
    }

    /**
     * Test case for endpointsGetBaseModelLog
     *
     * Gets a specific audio or transcription log for the default base model in a given language..
     *
     */
    public function testEndpointsGetBaseModelLog()
    {
    }

    /**
     * Test case for endpointsGetLog
     *
     * Gets a specific audio or transcription log for a given endpoint..
     *
     */
    public function testEndpointsGetLog()
    {
    }

    /**
     * Test case for endpointsList
     *
     * Gets the list of endpoints for the authenticated subscription..
     *
     */
    public function testEndpointsList()
    {
    }

    /**
     * Test case for endpointsListBaseModelLogs
     *
     * Gets the list of audio and transcription logs that have been stored when using the default base model of a given language..
     *
     */
    public function testEndpointsListBaseModelLogs()
    {
    }

    /**
     * Test case for endpointsListLogs
     *
     * Gets the list of audio and transcription logs that have been stored for a given endpoint..
     *
     */
    public function testEndpointsListLogs()
    {
    }

    /**
     * Test case for endpointsListSupportedLocales
     *
     * Gets a list of supported locales for endpoint creations..
     *
     */
    public function testEndpointsListSupportedLocales()
    {
    }

    /**
     * Test case for endpointsUpdate
     *
     * Updates the metadata of the endpoint identified by the given ID..
     *
     */
    public function testEndpointsUpdate()
    {
    }
}
